"use client";
import Link from "next/link"; import { useState } from "react"; import { Chapter, comments } from "@/lib/mockData"; import { useRole } from "./RoleProvider"; import styles from "./ui.module.css";
export function CategoryTabs(){return <div className={styles.tabs}>{["ทั้งหมด","แฟนตาซี","โรแมนติก","ลึกลับ","ไซไฟ","ชีวิตประจำวัน","ผจญภัย"].map(x=><button key={x}>{x}</button>)}</div>}
export function FilterBar(){return <div className={styles.filters}><label>แท็ก<select><option>ทุกแท็ก</option><option>เวทมนตร์</option><option>อบอุ่นหัวใจ</option></select></label><label>สถานะ<select><option>ทุกสถานะ</option><option>กำลังอัปเดต</option><option>จบแล้ว</option></select></label><label>ประเภท<select><option>NOVEL + COMIC</option><option>NOVEL</option><option>COMIC</option></select></label><label>เรียงตาม<select><option>ยอดนิยม</option><option>ยอดอ่าน</option><option>ยอดถูกใจ</option><option>ผู้ติดตาม</option><option>ล่าสุด</option></select></label></div>}
export function ChapterList({chapters,slug="library-after-rain",comic=false}:{chapters:Chapter[];slug?:string;comic?:boolean}){return <div className={styles.chapterList}>{chapters.map(ch=><Link className={styles.chapter} key={ch.number} href={comic?`/comic/${slug}/chapter/${ch.number}`:`/story/${slug}/chapter/${ch.number}`}><strong>ตอนที่ {ch.number}: {ch.title}</strong><small>อ่าน {ch.views.toLocaleString()} · ♥ {ch.likes}</small><small>{ch.published}</small></Link>)}</div>}
export function CommentList(){const {role}=useRole();const [dialog,setDialog]=useState(false);return <section><div className="sectionTitle"><h2>ความคิดเห็น</h2><span>{comments.length} ความคิดเห็น</span></div>{role==="guest"?<button className="secondaryButton" onClick={()=>setDialog(true)}>เข้าสู่ระบบเพื่อแสดงความคิดเห็น</button>:<div className="formRow"><input placeholder="เขียนความคิดเห็นแบบไม่ตอบเป็นเธรด"/><button>ส่งความคิดเห็น</button></div>}<div className={styles.comments}>{comments.map((c,i)=><article className={styles.comment} key={i}><div className={styles.commentHead}><strong>{c.user}</strong><span>{c.time}</span></div><p>{c.text}</p></article>)}</div>{dialog&&<LoginRequiredDialog onClose={()=>setDialog(false)}/>}</section>}
export function LoginRequiredDialog({onClose}:{onClose:()=>void}){return <div className={styles.modalBackdrop} role="dialog"><div className={styles.modal}><h2>เข้าสู่ระบบเพื่อทำรายการนี้</h2><p>สมาชิกจึงจะกดถูกใจบท ติดตามเรื่อง แสดงความคิดเห็น หรือรายงานเนื้อหาได้ การอ่านยังเปิดให้ทุกคน</p><div className={styles.modalActions}><button className="textButton" onClick={onClose}>ไว้ภายหลัง</button><Link className="primaryButton" href="/login">ไปหน้าเข้าสู่ระบบ</Link></div></div></div>}
export function ProtectedAction({children}:{children:React.ReactNode}){const {role}=useRole();const [open,setOpen]=useState(false);const [done,setDone]=useState(false);return <>{<button onClick={()=>role==="guest"?setOpen(true):setDone(!done)}>{done?"✓ ดำเนินการแล้ว":children}</button>}{open&&<LoginRequiredDialog onClose={()=>setOpen(false)}/>}</>}
export function EmptyState({title="ยังไม่มีข้อมูล",description="เมื่อมีรายการ ข้อมูลจะแสดงในพื้นที่นี้",action}:{title?:string;description?:string;action?:string}){return <div className={styles.empty}><div className={styles.emptyIcon}>◇</div><h3>{title}</h3><p>{description}</p>{action&&<button>{action}</button>}</div>}
export function ConfirmButton({label="ล้างประวัติ"}:{label?:string}){const [open,setOpen]=useState(false);return <>{<button className="dangerButton" onClick={()=>setOpen(true)}>{label}</button>}{open&&<div className={styles.modalBackdrop}><div className={styles.modal}><h2>ยืนยันการดำเนินการ</h2><p>นี่เป็นหน้าจอยืนยันตัวอย่าง ข้อมูลจำลองจะไม่ถูกเปลี่ยนแปลงจริง</p><div className={styles.modalActions}><button className="textButton" onClick={()=>setOpen(false)}>ยกเลิก</button><button onClick={()=>setOpen(false)}>ยืนยัน</button></div></div></div>}</>}
export const LoadingSkeleton=()=> <div className={styles.skeleton}/>;
